name: Build wheels

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: wheels-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: sdist + wheel (pure-Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install build backend
        run: |
          python -m pip install -U pip build
      - name: Build distributions
        run: |
          python -m build --sdist --wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gcfl-sim-dist
          path: dist/*

  # Optional: publish to PyPI when a release is published and token is present.
  publish:
    if: github.event_name == 'release' && github.event.action == 'published' && secrets.PYPI_API_TOKEN != ''
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: gcfl-sim-dist
          path: dist
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.10.3
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
